name: Knowledge Engineering Reference
markdown: redcarpet
pygments: true
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
baseurl: /onto_dot_ir
